# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/MitchSeigel/econ8310-assignment1/blob/main/assignment1.ipynb
"""

import pandas as pd
from prophet import Prophet

data = pd.read_csv("https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_train.csv")

data_p = data[['Timestamp','trips']]

data_p['Timestamp'] = pd.to_datetime(data_p['Timestamp'])
data_p = data_p.rename(columns={'Timestamp': 'ds', 'trips': 'y'})

model = Prophet()
modelFit = model.fit(data_p)

test_data = pd.read_csv("https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_test.csv")
test_data['Timestamp'] = pd.to_datetime(test_data['Timestamp'])
future = test_data.rename(columns={'Timestamp': 'ds'})

pred = modelFit.predict(future)

# pred = pred[['ds', 'trend']]
# pred['trend'] = pred['trend'].astype(int)
# pred = pred.set_index('ds')

pred = pred[['ds', 'yhat']]
pred['yhat'] = pred['yhat'].astype(int)
pred = pred.set_index('ds')

pred